"""empty message

Revision ID: 20e89eb059bf
Revises: 
Create Date: 2019-02-21 00:24:05.844563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e89eb059bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('sat_breakfast', sa.Boolean(), nullable=True),
    sa.Column('sat_lunch', sa.Boolean(), nullable=True),
    sa.Column('sat_dinner', sa.Boolean(), nullable=True),
    sa.Column('sun_breakfast', sa.Boolean(), nullable=True),
    sa.Column('sun_lunch', sa.Boolean(), nullable=True),
    sa.Column('dietary', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    # ### end Alembic commands ###
