"""empty message

Revision ID: ce163c991d48
Revises: 20e89eb059bf
Create Date: 2019-02-28 22:12:06.143176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce163c991d48'
down_revision = '20e89eb059bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('tshirt', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'tshirt')
    # ### end Alembic commands ###
